"""プロフィール画像追加

Revision ID: 8200d34df56f
Revises: b8c69e5eb69b
Create Date: 2023-10-29 05:24:53.835424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8200d34df56f'
down_revision = 'b8c69e5eb69b'
branch_labels = None
depends_on = None

 
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=150), nullable=False, server_default='default.jpg'))
        # この例では 'default.jpg' をデフォルト値として使用しています。適切なデフォルト値に変更してください。
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
