"""ドラッグアンドドロップ追加

Revision ID: d503245adb9b
Revises: 0f2b62b764a4
Create Date: 2023-11-22 22:54:53.229168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd503245adb9b'
down_revision = '0f2b62b764a4'
branch_labels = None
depends_on = None
 

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
